# Generated by Django 5.0.6 on 2024-12-03 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("datetime", models.DateTimeField(auto_now_add=True)),
                ("imgur_uploaded", models.BooleanField(default=False)),
                ("imgur_url", models.URLField(blank=True)),
                (
                    "image",
                    models.ImageField(
                        default="fallback.png",
                        upload_to="D:\\Projects\\Real Projects\\InstagramAutomation\\InstaAutomation\\media\\images",
                    ),
                ),
            ],
        ),
    ]
