# Generated by Django 5.0.6 on 2024-12-03 16:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0002_alter_image_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="datetime",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
