# Generated by Django 5.0.6 on 2024-12-09 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0003_alter_image_datetime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="title",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
