# Generated by Django 5.1.4 on 2024-12-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0004_alter_image_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="description",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
